apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      label: packops
  template:
    metadata:
      labels:
        label: packops
    spec:
      containers:
        - name: web-app
          image: farshadnikfetrat/prom-request:3
          ports:
            - containerPort: 8080
          env:
            - name: PROMETHEUS_METRICS_PORT
              value: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "metrics"
    prometheus.io/scrape: "true"
  name: web-app
  labels:
    label: svc-packops
spec:
  selector:
    label: packops
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: "metrics"
