apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: packops-scaler
  namespace: default
spec:
  scaleTargetRef:
    kind: Deployment
    name: nginx-deployment
    #  minReplicaCount: 2
  maxReplicaCount: 10
  cooldownPeriod: 10
  pollingInterval: 10
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://kube-prom-stack-kube-prome-prometheus.monitoring.svc.cluster.local:9090
        metricName: custom_metric
        query: "custom_metric"
        threshold: "1"
